export const weatherImages = {
  Sunny: require("../assets/Sun.png"),
  "Sunny ": require("../assets/Sun.png"),
  Clear: require("../assets/cloudy.png"),
  "Clear ": require("../assets/cloudy.png"),
  "Overcast ": require("../assets/cloudy.png"),
  Overcast: require("../assets/cloudy.png"),
  Cloudy: require("../assets/partly-cloudy.png"),
  "Cloudy ": require("../assets/partly-cloudy.png"),
  "Partly cloudy": require("../assets/partly-cloudy.png"),
  "Moderate rain": require("../assets/moderate rain.png"),
  "Patchy rain possible": require("../assets/moderate rain.png"),
  "Light rain": require("../assets/moderate rain.png"),
  "Moderate rain at times": require("../assets/partly-cloudy.png"),
  "Heavy rain": require("../assets/partly-cloudy.png"),
  "Heavy rain at times": require("../assets/heavy_rain.png"),
  "Light freezing rain": require("../assets/freezing rain.png"),
  "Moderate or heavy rain shower": require("../assets/rainy.png"),
  "Moderate or heavy rain with thunder": require("../assets/partly-cloudy.png"),
  other: require("../assets/cloudy.png"),
};
