export const weatherImages = {
  Sunny: require("../assets/3dSUN.png"),
  "Sunny ": require("../assets/3dSUN.png"),
  Clear: require("../assets/cloudy.png"),
  "Clear ": require("../assets/cloudy.png"),
  "Overcast ": require("../assets/cloudy.png"),
  Overcast: require("../assets/cloudy.png"),
  Cloudy: require("../assets/partly-cloudy.png"),
  "Cloudy ": require("../assets/partly-cloudy.png"),
  "Partly cloudy": require("../assets/partly-cloudy.png"),
  "Partly Cloudy": require("../assets/partly-cloudy.png"),
  "Partly Cloudy ": require("../assets/partly-cloudy.png"),
  "Moderate rain": require("../assets/moderate rain.png"),
  "Patchy rain nearby": require("../assets/moderate rain.png"),
  "Patchy light drizzle": require("../assets/moderate rain.png"),
  "Light rain": require("../assets/moderate rain.png"),
  "Light rain shower": require("../assets/moderate rain.png"),
  "Moderate rain at times": require("../assets/partly-cloudy.png"),
  "Heavy rain": require("../assets/heavy_rain.png"),
  "Heavy rain at times": require("../assets/heavy_rain.png"),
  "Light freezing rain": require("../assets/freezing rain.png"),
  "Moderate or heavy rain shower": require("../assets/rainy.png"),
  Mist: require("../assets/Mist.png"),
  "Thundery outbreaks in nearby": require("../assets/Rain with thunder.png"),
  other: require("../assets/cloudy.png"),
};
